// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const sessionResult = await supabase.auth.getSession();
    const session = sessionResult?.data?.session ?? null;
    const token = session?.access_token ?? null;

    // Attach header only if token exists; do not log the token value itself.
    return next({ headers: token ? { Authorization: `Bearer ${token}` } : {} });
  },
)
